// Lista de títulos para pesquisa 
var titulosTextos = {
    "ADC 58  COM PAGAMENTO REALIZADO": "Nesse sentido, há que se considerar a modulação prevista na mencionada ADC relativamente aos casos em que houver sido realizado pagamento de valores:\n\n(i) são reputados válidos e não ensejarão qualquer rediscussão (na ação em curso ou em nova demanda, incluindo ação rescisória) todos os pagamentos realizados utilizando a TR (IPCA-E ou qualquer outro índice), no tempo e modo oportunos (de forma extrajudicial ou judicial, inclusive depósitos judiciais) e os juros de mora de 1% ao mês (...).",
    "ADC 58 - PROCESSOS ANTIGOS": "Tendo em vista serem o período contratual do autor e o ajuizamento da ação anteriores à data de início do IPCA-E e da taxa Selic, devem ser aplicados os seguintes parâmetros para atualização dos valores:\n\n1 - Na fase pré-judicial, os valores devem ser corrigidos pelo IPCA até dezembro/1991 e pelo IPCA-E de janeiro/1992 até o ajuizamento.\n\n2 - Na fase judicial, devem ser aplicados juros de 1% a.m. do ajuizamento até janeiro/1995, modulando-se para Selic (Receita Federal) de fevereiro/1995 até a data do cálculo.\n\n*\n\nPara contratos anteriores a janeiro/1980, utilizar Tabela Única de Atualização de Débitos Trabalhistas.",
    "ATUALIZAÇÃO ADC 58 – JUROS TRD SIMPLES": "PROCESSO nº 0100071-49.2019.5.01.0015 (AP)\n\nRELATOR: ALBA VALERIA GUEDES FERNANDES DA SILVA\n\nEMENTA\n\nAGRAVO DE PETIÇÃO. CORREÇÃO MONETÁRIA E JUROS. ÍNDICE NÃO DEFINIDO NO TÍTULO EXECUTIVO. APLICAÇÃO DA DECISÃO DEFINITIVA DA ADC 58. Considerando que inexiste definição expressa dos índices de correção monetária e juros no título executivo e a decisão definitiva do STF na ADC nº 58, deve ser aplicado o IPCA-E na fase pré-judicial e a SELIC a partir do ajuizamento para correção do débito, mantendo-se a aplicação dos juros de mora equivalentes à TR na fase pré-judicial, conforme art. 39, §1°, da Lei 8177/91, que permanece em vigor e já que somente a SELIC cumula correção e juros. \n\nImportante salientar, até mesmo para evitar embargos de declaração, que a incidência de juros de mora está em consonância com o que estou decidido pelo STF na ADC 58, conforme consta do item 6 da ementa do julgado: (...) 6. Em relação à fase extrajudicial, ou seja, a que antecede o ajuizamento das ações trabalhistas, deverá ser utilizado como indexador o IPCA-E acumulado no período de janeiro a dezembro de 2000. A partir de janeiro de 2001, deverá ser utilizado o IPCA-E mensal (IPCA-15/IBGE), em razão da extinção da UFIR como indexador, nos termos do art. 29, §3º, da MP 1.973-67/2000. Além da indexação, serão aplicados os juros legais. (art. 39, caput, da Lei 8.177, de 1991). (STF, Tribunal Pleno, ADC-58, Rel. Min. Gilmar Mendes, Data de Publicação: 07.04.2021) - grifo nosso",
    "ADICIONAL DE PERICULOSIDADE - BASE DE CÁLCULO": "Súmula nº 191\n\nI – O adicional de periculosidade incide apenas sobre o salário básico e não sobre este acrescido de outros adicionais\n\nhttp://www3.tst.jus.br/jurisprudencia/Sumulas_com_indice/Sumulas_Ind_151_200.html#SUM-191",
    "ATUALIZAÇÃO - ADC 58 e 59": "Nesse sentido, devem ser os cálculos retificados, adotando-se as regras fixadas na ADC n. 58: correção dos valores pelo IPCA-E na fase pré-judicial e, a partir da citação, incidência da taxa SELIC (art. 406 do Código Civil).",
    "ATUALIZAÇÃO CÁLCULOS - EE e AP": "entendo não assistir razão à executada quanto à necessidade de se limitarem os juros à data do pagamento realizado por ocasião dos embargos à execução, vez que o referido depósito não propicia o imediato levantamento do crédito do exequente, conforme estabelece a Súmula 4 do TRT da 1ª Região.\n\nSÚMULA Nº 4 Contagem de juros. Depósito garantidor da dívida ou adimplemento total da obrigação. Cessação da contagem. CLT e lei de execução fiscal. I - A incidência de juros de mora, assim como da correção monetária, sobre o crédito trabalhista é regulada integralmente pela Lei 8.177/1991 e, portanto, nesse aspecto, não é aplicável o artigo 9º, § 4º, da Lei de Executivo Fiscal. II – Somente o adimplemento integral da dívida, assim considerado o depósito que propicia o imediato levantamento, fará cessar a contagem de juros moratórios.\n\nhttps://www.trt1.jus.br/documents/22365/3111637/S%C3%BAmulas+-+arquivo+completo+12mar2020+com+logo.pdf/c04a9bb3-b0c4-7d16-7c80-c8393c00f063",
    "AVISO PRÉVIO – PROPORCIONALIDADE": "LEI Nº 12.506, DE 11 DE OUTUBRO DE 2011.\n\nParágrafo único.  Ao aviso prévio previsto neste artigo serão acrescidos 3 (três) dias por ano de serviço prestado na mesma empresa, até o máximo de 60 (sessenta) dias, perfazendo um total de até 90 (noventa) dias.",
    "CÁLCULO DA CONTRIBUIÇÃO PREVIDENCIÁRIA – RESPONSABILIDADE DAS PARTES (ART. 879 DA CLT)": "Quanto ao cálculo da contribuição previdenciária, acredito ser de responsabilidade das partes a sua apuração, ante o que consta do Art. 879, parágrafo 1-b, da CLT.",
    "CÁLCULO DE HORAS EXTRAS, COMISSIONISTA": "Súmula nº 340 do TST\nCOMISSIONISTA. HORAS EXTRAS (nova redação) - Res. 121/2003, DJ 19, 20 e 21.11.2003\n\nO empregado, sujeito a controle de horário, remunerado à base de comissões, tem direito ao adicional de, no mínimo, 50% (cinqüenta por cento) pelo trabalho em horas extras, calculado sobre o valor-hora das comissões recebidas no mês, considerando-se como divisor o número de horas efetivamente trabalhadas.",
    "CÁLCULO DO IR": "No que diz respeito ao cálculo do IR, creio deveria ter o autor (1) divido a base de cálculo total pelo número de meses sobre os quais incide IR; (2) multiplicado o resultado da divisão anterior pela alíquota própria, conforme dados constantes da IN RFB Nº 1558/2015; (3) subtraído deste produto o redutor indicado na IN antes referida; (4) multiplicado a diferença pelo número de meses sobre os quais houve incidência de IR.",
    "CÁLCULO RSR  X  DIVISÃO POR 6": "Sobre a apuração do RSR, creio equivocar-se o réu, haja vista que o método adotado pela contadoria não apenas é válido como é ainda mais preciso que a divisão por seis.",
    "COBRANÇA GRADUAL DA COTA PREVIDENCIÁRIA": "RECLAMADAS TRANSFORMADAS EM SOCIEDADES DE FINS ECONÔMICOS\n\nLEI Nº 11.096, DE 13 DE JANEIRO DE 2005\n\nArt. 11. As entidades beneficentes de assistência social que atuem no ensino superior poderão, mediante assinatura de termo de adesão no Ministério da Educação, adotar as regras do Prouni, contidas nesta Lei, para seleção dos estudantes beneficiados com bolsas integrais e bolsas parciais de 50% (cinqüenta por cento) ou de 25% (vinte e cinco por cento), em especial as regras previstas no art. 3º e no inciso II do caput e §§ 1º e 2º do art. 7º desta Lei, comprometendo- se, pelo prazo de vigência do termo de adesão, limitado a 10 (dez) anos, renovável por iguais períodos, e respeitado o disposto no art. 10 desta Lei, ao atendimento das seguintes condições:\n\nArt. 13. As pessoas jurídicas de direito privado, mantenedoras de instituições de ensino superior, sem fins lucrativos, que adotarem as regras de seleção de estudantes bolsistas a que se refere o art. 11 desta Lei e que estejam no gozo da isenção da contribuição para a seguridade social de que trata o § 7º do art. 195 da Constituição Federal, que optarem, a partir da data de publicação desta Lei, por transformar sua natureza jurídica em sociedade de fins econômicos, na forma facultada pelo art. 7º-A da Lei nº 9.131, de 24 de novembro de 1995, passarão a pagar a quota patronal para a previdência social de forma gradual, durante o prazo de 5 (cinco) anos, na razão de 20% (vinte por cento) do valor devido a cada ano, cumulativamente, até atingir o valor integral das contribuições devidas.\n\nEXEMPLO\n\nDEVIDOS 22%\n\n1º ANO – 22%/5 X 1\n\n2º ANO – 22%/5 X 2\n\n3º ANO – 22%/5 X 3\n\n4º ANO – 22%/5 X 4\n\n5º ANO – 22%/5 X 5",    
    "CONTRIBUÇÃO DA PETROS": "Dra. Adriana entende que as contribuições da petro devem ser deduzidas dos cálculos de implementação de aposentadoria.",
    "CONTRIBUIÇÃO DE TERCEIROS – INCOMPETÊNCIA DA JUSTIÇA DO TRABALHO": "não é da competência da justiça do trabalho a execução de contribuição em favor de terceiros, conforme estabelece a Súmula 36 do TRT/RJ.\n\nSÚMULA Nº 36\n\nContribuições sociais destinadas a terceiros. Incompetência absoluta. A Justiça do Trabalho é incompetente para a execução de contribuições em favor de terceiros, destinadas ao denominado “Sistema S”.",
    "CONTRIBUIÇÃO PREVIDENCIÁRIA PATRONAL – ISENÇÃO (ENTIDADES BENEFICENTES DE ASSISTÊNCIA SOCIAL)": "Deveria o réu ter trazido aos autos documento fornecido pelo INSS, concedendo-lhe isenção relativa ao recolhimento da cota previdenciária patronal.\n\nNão serve a certidão de entidade beneficente de assistência social. É preciso documento fornecido pelo INSS isentando a empresa a contribuição social.\n\nLei 12101, 27/11/09",
    "CONTRIBUIÇÃO PREVIDENCIÁRIO QUOTA-PARTE DO AUTOR – RESPONSABILIDADE DA RÉ": "LEI 8212/91\n\nARTIGO 33, §5\n\nhttp://www.planalto.gov.br/ccivil_03/leis/l8212cons.htm",
    "CORREÇÃO MONETÁRIA – MÊS SUBSEQUENTE": "Súmula nº 381 do TST\n\nCORREÇÃO MONETÁRIA. SALÁRIO. ART. 459 DA CLT (conversão da Orientação Jurisprudencial nº 124 da SBDI-1) - Res. 129/2005, DJ 20, 22 e 25.04.2005\n\nO pagamento dos salários até o 5º dia útil do mês subsequente ao vencido não está sujeito à correção monetária. Se essa data limite for ultrapassada, incidirá o índice da correção monetária do mês subsequente ao da prestação dos serviços, a partir do dia 1º. (ex-OJ nº 124 da SBDI-1 - inserida em 20.04.1998)",
    "CORREIOS – EQUIPARA-SE À FAZENDA PÚBLICA": "Quanto aos índices de atualização monetária, creio equivocar-se, tendo em vista que o réu equipara-se à Fazenda Pública, conforme decisão do STF relativa ao RE 220906.\n\nO art. 12 do Decreto-Lei nº 509/1969 estende à ECT os privilégios referentes a foro, prazos e custas processuais concedidos à Fazendo Pública; dispositivo legal que foi declarado recepcionado pela CF88, conforme decidiu o STF no RE 220906/DF\n\nRE 220906.",
    "COTAS PREVIDENCIÁRIAS – ATUALIZAÇÃO PELA TR": "Quanto à atualização das cotas previdenciárias, creio equivocar-se o réu, tendo em vista que o entendimento deste Juízo é no sentido de que os valores devidos a tal título devem ser corrigidos pela TR, conforme artigo 879 da CLT, que determina, sem ressalvas, que a atualização dos créditos decorrentes de condenação judicial sejam feitos feita pela Taxa Referencial (TR).",
    "DANOS MORAIS": "Súmula nº 439 do TST\n\nDANOS MORAIS. JUROS DE MORA E ATUALIZAÇÃO MONETÁRIA. TERMO INICIAL - Res. 185/2012, DEJT divulgado em 25, 26 e 27.09.2012\n\nNas condenações por dano moral, a atualização monetária é devida a partir da data da decisão de arbitramento ou de alteração do valor. Os juros incidem desde o ajuizamento da ação, nos termos do art. 883 da CLT.",
    "DECADÊNCIA DO CRÉDITO PREVIDENCIÁRIO": "Sem razão.\n\nTranscrevo ementa de acórdão proferido em ação similar:\n\nPROCESSO nº 0010219-65.2015.5.01.0011 (AP)\n\nAGRAVANTE: CLAUDIO DA SILVA SARGO\n\nAGRAVADO: GLOBO COMUNICACAO E PARTICIPACOES S/A\n\nRELATOR: DESEMBARGADOR DO TRABALHO ENOQUE RIBEIRO DOS SANTOS\n\nEMENTA\n\nAGRAVO DE PETIÇÃO DA EXECUTADA. CONTRIBUIÇÕES PREVIDENCIÁRIAS.\n\nDECADÊNCIA DO CRÉDITO EXECUTADO.NÃO CONFIGURAÇÃO.A jurisprudência majoritária das Cortes trabalhistas pátrias adotam entendimento no sentido de que somente com a ciência, à União Federal, da decisão que reconhece o direito, é que tem início a contagem do prazo decadencial de cinco anos alusivo ao crédito tributário (art. 174 do CTN). Recurso a que se nega provimento, no particular.\n\nComo in casu não foi dada ciência à União, não há falar em decadência. Ademais a declaração do direito só se deu com o trânsito em julgado da decisão.",
    "DEDUÇÃO DAS HORAS EXTRAS PAGAS": "OJ-SDI1-415 HORAS EXTRAS. RECONHECIMENTO EM JUÍ- ZO. CRITÉRIO DE DEDUÇÃO/ABATIMENTO DOS VALORES COMPROVADAMENTE PAGOS NO CURSO DO CONTRATO DE TRABALHO. (DEJT divulgado em 14, 15 e 16.02.2012)\n\nA dedução das horas extras comprovadamente pagas daquelas reconhecidas em juízo não pode ser limitada ao mês de apuração, devendo ser integral e aferida pelo total das horas extraordinárias quitadas durante o período imprescrito do contrato de trabalho.",
    "DESONERAÇÃO DA FOLHA DE PAGAMENTO - Lei n. 12715/2012": "No que se refere à Lei de Desoneração da Folha de Pagamento, é de entendimento do Juízo que inexiste previsão legal para que a referida norma alcance os créditos reconhecidos judicialmente.\n\nAlém disso, o regramento invocado se restringe aos contratos de trabalho em curso, referentes às contribuições previdenciárias decorrentes do pagamento mês a mês das verbas trabalhistas, o que não se aplica ao presente caso; inclusive porque o recolhimento das contribuições previdenciárias incidentes sobre créditos trabalhistas oriundos de decisões judiciais possui regramento legal específico, nos termos dos artigos 43 e 44 da Lei 8.212/91, artigo 276, §6º, do Decreto 3.048/99 e Súmula 368 do TST.",
    "DOCUMENTOS JUNTADOS NA FASE DE LIQUIDAÇÃO": "não assistir razão ao autor no que diz respeito à utilização dos documentos juntados como parâmetro para os cálculos, tendo em vista o entendimento deste Juízo de que as evidências documentais que venham servir à feitura dos cálculos podem ser juntadas pela partes também na fase de liquidação, a menos que em sentença se tenha registrado restrição expressa neste sentido.",
    "ENTIDADE BENEFICENTE DE ASSISTÊNCIA SOCIAL – ISENÇÃO INSS": "Não serve a certidão de entidade beneficente de assistência social. É preciso documento fornecido pelo INSS isentando a empresa a contribuição social.\n\nLei 12101, 27/11/09\n\nQuanto à isenção da contribuição previdenciária patronal, creio deveria ter o réu trazido aos autos documento fornecido pelo INSS, desobrigando a empresa do recolhimento, haja vista que, das entidades beneficentes de assistência social, somente as que atenderem às exigências previstas na Lei 12101 de 2009 terão direito à pretendida isenção.",
    "ESCALA 12 X 36 – PAGAMENTO EM DOBRO NO FERIADO": "Súmula nº 444 do TST\n\nJORNADA DE TRABALHO. NORMA COLETIVA. LEI. ESCALA DE 12 POR 36. VALIDADE. - Res. 185/2012, DEJT divulgado em 25, 26 e 27.09.2012  - republicada em decorrência do despacho proferido no processo TST-PA-504.280/2012.2 - DEJT divulgado em 26.11.2012\n\nÉ valida, em caráter excepcional, a jornada de doze horas de trabalho por trinta e seis de descanso, prevista em lei ou ajustada exclusivamente mediante acordo coletivo de trabalho ou convenção coletiva de trabalho, assegurada a remuneração em dobro dos feriados trabalhados. O empregado não tem direito ao pagamento de adicional referente ao labor prestado na décima primeira e décima segunda horas.",
    "EXECUÇÃO DAS COTAS PREVIDENCIÁRIAS – COMPETÊNCIA DA JUSTIÇA DO TRABALHO": "Súmula 368 do TST\n\nhttp://www3.tst.jus.br/jurisprudencia/Sumulas_com_indice/Sumulas_Ind_351_400.html#SUM-368\n\nArt. 114, inciso VIII, CFhttp://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm\n\nDecreto n º 3.048/1999\n\nRTE\n\nalíquotas contribuição autoral, art. 198,\n\nobservado o limite máximo do salário de contribuição (ex-OJs nºs 32 e 228 da SBDI-1 – inseridas, respectivamente, em 14.03.1994 e 20.06.2001).\n\nRDA\n\npercentual contribuição patronal artigo 201, inciso II\n\nhttp://www.planalto.gov.br/ccivil_03/decreto/d3048.htm", 
    "FÉRIAS – PRESCRIÇÃO": "acredito equivocar-se o réu, haja vista que a prescrição do direito de reclamar a concessão das férias ou o pagamento da respectiva remuneração é contada do término do período concessivo, conforme dispõem os artigos 149 e 134 da CLT.",
    "FÉRIAS VENCIDAS - BASE DE CÁLCULO": "Súmula nº 7 do TST\n\nFÉRIAS (mantida) - Res. 121/2003, DJ 19, 20 e 21.11.2003\n\nA indenização pelo não-deferimento das férias no tempo oportuno será calculada com base na remuneração devida ao empregado na época da reclamação ou, se for o caso, na da extinção do contrato.",
    "FILANTROPIA": "Súmula nº 7 do TST\n\nFÉRIAS (mantida) - Res. 121/2003, DJ 19, 20 e 21.11.2003\n\nA indenização pelo não-deferimento das férias no tempo oportuno será calculada com base na remuneração devida ao empregado na época da reclamação ou, se for o caso, na da extinção do contrato.",    
    "HONORÁRIOS SUCUMJBENCIAIS": "Dos honorários sucumbenciais em sede de execução autônoma\n\nINDEFIRO.\n\nOs honorários de sucumbência previstos no art. 791-A da CLT se referem aos devidos na fase de conhecimento, não havendo qualquer menção a serem devidos na fase expropriatória.\n\nAdemais, relembro que na ação original não foram deferidos honorários advocatícios.\n\nDos honorários contratuais\n\nO art. 22 da Lei nº 8906/94 contém a seguinte disposição: 'se o advogado fizer juntar aos autos o seu contrato de honorários antes de expedir-se o mandado de levantamento ou precatório, o juiz deve determinar que lhe sejam pagos diretamente, por dedução da quantia a ser recebida pelo constituinte, salvo se este provar que já os pagou.'\n\nConforme dados da peça de ingresso, o autor postulou a reserva de honorários contratuais à razão de 10% conforme pedido de letra ‘c’ e juntou aos autos contrato de honorários no id 9ded1a5 - Pág. 1.\n\nAssim, DEFIRO a reserva de 10% sobre o valor do crédito da autora a título de honorários advocatícios contratuais.",
    "INCIDÊNCIA DE JUROS SOBRE MULTAS DEFERIDAS EM SENTENÇA": "Não assistir razão ao réu quanto à indevida apuração de juros sobre as multas deferidas em sentença, vez que a incidência de juros deve se dar sobre a totalidade da condenação após deduzidas as cotas previdenciárias e o imposto de renda.",
    "INSS – JUROS SELIC": "Não assiste razão ao réu, uma vez que são aplicáveis os juros SELIC às contribuições previdenciárias pagas em atraso, conforme estabelecem as alterações que o artigo 26 da Lei nº 11.941 de 27 de maio de 2009 produz sobre a Lei nº 8.212, de 24 de julho de 1991.\n\n**\n\nInformo a V. Exa. que entendo não assistir razão ao réu quanto ao equívoco na apuração das contribuições previdenciárias, ante o que consta da Súmula 66 deste Tribunal:\n\nSÚMULA Nº 66 Contribuição previdenciária sobre o crédito judicial trabalhista. Fato gerador. Acréscimos legais moratórios. Nova redação do art. 43 da Lei 8.212/91. Vigência. Regime híbrido de apuração. I - Para prestação de serviços ocorrida até 04/03/2009,inclusive, o fato gerador da contribuição previdenciária vinculada ao processo trabalhista é a constituição do crédito. Seu recolhimento dar-se-á até o dia 2 do mês subsequente à liquidação do julgado, de acordo com o art. 276 do Decreto 3.048/1999.Extrapolado este prazo, a contribuição previdenciária será corrigida monetariamente e acrescida de juros e multa moratórios. II - Para prestação de serviços ocorrida a partir de 05/03/2009,inclusive, o fato gerador da contribuição previdenciária é a prestação de serviços, nos termos do art. 43 da Lei 8.212/91, com redação dada pela Lei 11.941/2009, com juros e correção monetária computados a partir dos meses de competência e recolhimento na mesma data prevista para o pagamento do crédito judicial trabalhista\n\n",
    "INSS PATRONAL - SIMPLES NACIONAL": "assistir razão ao réu, quanto ao não cabimento das cotas previdenciárias de sua responsabilidade, haja vista ter sido optante do 'Simples Nacional' por ocasião da prestação de serviços.  Nesse sentido, este Juízo acompanha a Súmula 66 deste E. Tribunal, que dispõe regime híbrido de apuração, conforme abaixo se transcreve:\n\nSÚMULA 66\n\nCONTRIBUIÇÃO PREVIDENCIÁRIA SOBRE O CRÉDITO JUDICIAL TRABALHISTA. FATO GERADOR. ACRÉSCIMOS LEGAIS MORATÓRIOS. NOVA REDAÇÃO DO ART. 43 DA LEI 8.212/91. VIGÊNCIA. REGIME HÍBRIDO DE APURAÇÃO.\n\nI - Para prestação de serviços ocorrida até 04/03/2009, inclusive, o fato gerador da contribuição previdenciária vinculada ao processo trabalhista é a constituição do crédito. Seu recolhimento dar-se-á até o dia 2 do mês subsequente à liquidação do julgado, de acordo com o art. 276 do Decreto 3.048/1999. Extrapolado este prazo, a contribuição previdenciária será corrigida monetariamente e acrescida de juros e multa moratórios. II - Para prestação de serviços ocorrida a partir de 05/03/2009, inclusive, o fato gerador da contribuição previdenciária é a prestação de serviços, nos termos do art. 43 da Lei 8.212/91, com redação dada pela Lei 11.941/2009, com juros e correção monetária computados a partir dos meses de competência e recolhimento na mesma data prevista para o pagamento do crédito judicial trabalhista.\n\n",
    "JUROS FAZENDA PÚBLICA": "JUROS – FAZENDA PÚBLICA\n\nLEI 9.494 DE 1997\n\nhttp://www.planalto.gov.br/ccivil_03/leis/l9494.htm\n\nOJ 07 TST\n\nhttp://www3.tst.jus.br/jurisprudencia/OJ_Pleno/n_TP_01.html#TEMA7",
    "JUROS SELIC SIMPLES – JUROS SELIC (RECEITA FEDERAL)": "A esse respeito, o item 7, da minuta do acórdão da ADC 58/59 é claro ao determinar:\n\n'7. Em relação à fase judicial, a atualização dos débitos judiciais deve ser efetuada pela taxa referencial do Sistema Especial de Liquidação e Custódia – SELIC, considerando que ela incide como juros moratórios dos tributos federais (arts. 13, da Lei 9.065/95; 84 da Lei 8.981/95; 39, §4º, da Lei 9.250/95; 61, §3º da Lei 9.430/96; e 30 da Lei 10.522/02).'",
    "JUROS SOBRE VALOR LÍQUIDO": "Quanto aos juros de mora, entendo devam ser aplicados sobre o valor líquido devido autor, uma vez que a “condenação” a que se refere o art. 883 da CLT corresponde ao crédito a ser recebido pelo empregado, e não àqueles devidos à Previdência Social e à Receita Federal.",
    "MASSA FALIDA - ATUALIZAÇÃO": "assistir razão ao réu quanto à limitação da incidência do juros de mora até a data da falência. No que se refere à correção monetária, entretanto, acredito equivocar-se, haja vista o entendimento do Juízo no sentido de que tal incidência deve dar-se até a data do cálculo.",
    "MÉDIA FISICA - HORAS EXTRAS": "No que diz respeito à inobservância da média duodecimal para o cálculo do reflexo das horas extras sobre verbas rescisórias, creio equivocar-se o réu, já que a média física do labor extraordinário deve ser apurada de acordo com o número de meses do respectivo interstício a ser considerado.\n\nTodavia, o autor apura as repercussões com base em média única, quando cabem médias distintas segundo a verba resilitória sobre a qual incide o reflexo.",
    "MULTA DE 40% SOBRE AVISO PRÉVIO": "Sobre o não cabimento da multa de 40% sobre aviso prévio, entendo equivocar-se o réu, já que a referida indenização deve ser apurada sobre total depositado a título de FGTS, que, à sua vez, deve incidir sobre o aviso prévio, conforme estabelecido na Súmula 205 do TST",
    "DA NÃO COMPENSAÇÃO DO VALOR PAGO A TÍTULO DE HORAS EXTRAS QUANDO A MAIOR": "entendo assistir razão à ré quanto à necessidade de se compensarem os valores pagos e devidos a título de horas extras, ante o o que consta da OJ n. 415 da SDI I do TST.",
    "OJ 54 TST – ARTIGO 412 DO CODIGO CIVIL": "DRA ADRIANA SEGUE A OJ 54 TST\n\nArt. 412. O valor da cominação imposta na cláusula penal não pode exceder o da obrigação principal.\n\nMULTA. CLÁUSULA PENAL. VALOR SUPERIOR AO PRINCIPAL. (título alterado, inserido dispositivo e atualizada a legislação, DJ 20.04.2005)\n\nO valor da multa estipulada em cláusula penal, ainda que diária, não poderá ser superior à obrigação principal corrigida, em virtude da aplicação do artigo 412 do Código Civil de 2002(art. 920 do Código Civil de 1916).",
    "PERÍODOS DE AFASTAMENTO – RECEBIMENTO DE SALÁRIO": "Abono médico (até 15 dias) - recebe remuneração\n\nLicença INSS - não recebe remuneração\n\nSuspensão de contrato de trabalho (lei de greve) - se não recebeu salário, não recebe diferenças.",
    "PRÊMIOS, ABONOS E DIÁRIAS DE VIAGEM – BASE DE CALC HORAS EXTRAS": "Entendo não assistir razão ao autor quanto à necessidade de se incluir da verba recebida a título de prêmio na base de cálculo das horas extras, ante o que consta do art. 257, § 2, da CLT, a esse respeito:\n\n§ 2o  As importâncias, ainda que habituais, pagas a título de ajuda de custo, auxílio-alimentação, vedado seu pagamento em dinheiro, diárias para viagem, prêmios e abonos não integram a remuneração do empregado, não se incorporam ao contrato de trabalho e não constituem base de incidência de qualquer encargo trabalhista e previdenciário. (Redação dada pela Lei nº 13.467, de 2017)\n\n*\n\n Entendo não assistir razão ao autor quanto à necessidade de se incluir da verba recebida a título de abono na base de cálculo das horas extras, ante o que consta do art. 257, § 2, da CLT, a esse respeito:\n\n§ 2o  As importâncias, ainda que habituais, pagas a título de ajuda de custo, auxílio-alimentação, vedado seu pagamento em dinheiro, diárias para viagem, prêmios e abonos não integram a remuneração do empregado, não se incorporam ao contrato de trabalho e não constituem base de incidência de qualquer encargo trabalhista e previdenciário. (Redação dada pela Lei nº 13.467, de 2017)\n\n*\n\nEntendo não assistir razão ao autor quanto à necessidade de se incluir da verba recebida a título de diária de viagem na base de cálculo das horas extras, ante o que consta do art. 257, § 2, da CLT, a esse respeito:\n\n§ 2o  As importâncias, ainda que habituais, pagas a título de ajuda de custo, auxílio-alimentação, vedado seu pagamento em dinheiro, diárias para viagem, prêmios e abonos não integram a remuneração do empregado, não se incorporam ao contrato de trabalho e não constituem base de incidência de qualquer encargo trabalhista e previdenciário. (Redação dada pela Lei nº 13.467, de 2017)",
    "PREVIDÊNCIA SOCIAL – ASSOCIAÇÃO DESPORTIVA": "CONTRIBUIÇÃO EMPRESARIAL DA ASSOCIAÇÃO DESPORTIVA QUE MANTÉM EQUIPE DE FUTEBOL PROFISSIONAL DESTINADA À SEGURIDADE SOCIAL\n\nAs associações desportivas que mantém equipe de futebol profissional recolhem contribuição previdenciária sobre 5% de sua receita bruta\n\nSão isentas de recolhimento em folha salarial\n\nLEI 8.212/91\n\nARTIGO 22\n\n§ 6º A contribuição empresarial da associação desportiva que mantém equipe de futebol profissional destinada à Seguridade Social, em substituição à prevista nos incisos I e II deste artigo, corresponde a cinco por cento da receita bruta, decorrente dos espetáculos desportivos de que participem em todo território nacional em qualquer modalidade desportiva, inclusive jogos internacionais, e de qualquer forma de patrocínio, licenciamento de uso de marcas e símbolos, publicidade, propaganda e de transmissão de espetáculos desportivos. (Incluído pela Lei nº 9.528, de 10.12.97)",
    "PRORROGAÇÃO DA JORNADA NOTURNA": "Súmula nº 60 do TST\n\nADICIONAL NOTURNO. INTEGRAÇÃO NO SALÁRIO E PRORROGAÇÃO EM HORÁRIO DIURNO (incorporada a Orientação Jurisprudencial nº 6 da SBDI-1) - Res. 129/2005, DJ 20, 22 e 25.04.2005\n\nI - O adicional noturno, pago com habitualidade, integra o salário do empregado para todos os efeitos. (ex-Súmula nº 60 - RA 105/1974, DJ 24.10.1974)\n\nII - Cumprida integralmente a jornada no período noturno e prorrogada esta, devido é também o adicional quanto às horas prorrogadas. Exegese do art. 73, § 5º, da CLT. (ex-OJ nº 6 da SBDI-1 - inserida em 25.11.1996)\n\nObs: A prorrogação da jornada noturna para além das 5 hs é também considerada no cálculo da hora ficta reduzida.",
    "RECUPERAÇÃO JUDICIAL – CORREÇÃO MONETÁRIA": "não assistir razão ao réu quanto à limitação dos juros nos casos de empresa em recuperação judicial, tendo em vista que o entendimento deste Juízo é de que a limitação do cômputo dos juros prevista no art. 124 da Lei 11.101/2005 concerne apenas à massa falida, não havendo qualquer restrição à incidência de juros de mora e correção monetária à empresa em recuperação judicial.",
    "RECUPERAÇÃO JUDICIAL SUBSID – ATUAL LIMITADA": "Sobre a necessidade de se limitarem os cálculos por estar a empresa em recuperação judicial, entende o Juízo que a questão deve ser avaliada na hipótese de redirecionamento da execução.",
    "REFLEXO DE HORAS EXTRAS EM RSR (COMISSIONISTA)": "Entendo não assistir razão ao réu quanto ao não cabimento da inclusão dos feriados na apuração do reflexo de horas extras sobre RSR. Tendo em vista tratar-se de horas extras com base em comissão, deve-se ter em conta que o pagamento da comissão não inclui feriados não trabalhados, pelo que os reflexos com base em comissão sobre RSR devem, portanto, contemplá-los.",
    "REPOUSO SEMANAL REMUNERADO – FERIADOS NÃO ENTRAM NO MULTIPLICADOR": "Os feriados não deveriam ser incluídos no multiplicador, haja vista não equivalerem aos dias de descanso semanal remunerado indicados no art.1º da lei 605/49.\n\nRegra:\n\nMensalista\n\núteis X repousos\n\nComissionista (puro?)\n\nTrabalhou feriado - Úteis X repousos\n\nNão trabalhou feriado - Úteis X repousos e feriados",
    "SALÁRIO DE CONTRIBUIÇÃO": "http://www.normaslegais.com.br/guia/clientes/contribuicoes-seguridade-social-salario-contribuicao.htm\n\nEntende-se por salário de contribuição:\n\na) Para o empregado e trabalhador avulso: a remuneração auferida em uma ou mais empresas, assim entendida a totalidade dos rendimentos pagos, devidos ou creditados a qualquer título, durante o mês, destinados a retribuir o trabalho, qualquer que seja a sua forma, inclusive as gorjetas, os ganhos habituais sob a forma de utilidades e os adiantamentos decorrentes de reajuste salarial, quer pelos serviços efetivamente prestados, quer pelo tempo à disposição do empregador ou tomador de serviços nos termos da lei ou do contrato ou, ainda, de convenção ou acordo coletivo de trabalho ou sentença normativa;\n\nb) Para o empregado doméstico: a remuneração registrada na CTPS, observadas as normas a serem estabelecidas em regulamento para comprovação do vínculo empregatício e do valor da remuneração;",
    "SAT – ALÍQUOTA DE CONTRIBUIÇÃO PARA O SEGURO DE ACIDENTE DE TRABALHO AFERIDA PELO GRAU DE RISCO DESENVOLVIDO EM CADA EMPRESA": "DECRETO Nº 6.957, DE 9 DE SETEMBRO DE 2009.\n\nhttp://www.planalto.gov.br/ccivil_03/_Ato2007-2010/2009/Decreto/D6957.htm\n\nEntendo equivocar-se no que se refere ao percentual do Gilrat, vez que, conforme o Anexo V do Decreto 6.957, de 9 de setembro de 2009, a alíquota a ser aplicada segundo o grau de risco característico da atividade desenvolvida pela empresa ré é de 3%.\n\nDECRETO Nº 6.257, DE 19 DE NOVEMBRO DE 2007.\n\nhttp://www.planalto.gov.br/ccivil_03/_Ato2007-2010/2007/Decreto/D6257.htm\n\nDECRETO Nº 6.042, DE 12 DE FEVEREIRO DE 2007.\n\nhttp://www.planalto.gov.br/ccivil_03/_Ato2007-2010/2007/Decreto/D6042.htm\n\nDECRETO No 3.048, DE 6 DE MAIO DE 1999.\n\nhttp://www.planalto.gov.br/ccivil_03/decreto/D3048.htm#anexov.",
    "SEGURO DESEMPREGO - TABELA": "http://trabalho.gov.br/index.php/seguro-desemprego/modalidades/seguro-desemprego-formal",
    "TRABALHO EM DOMINGOS E FERIADOS - sem prejuízo do RSR": "Súmula nº 146 do TST\n\nTRABALHO EM DOMINGOS E FERIADOS, NÃO COMPENSADO (incorporada a Orientação Jurisprudencial nº 93 da SBDI-1) - Res. 121/2003, DJ 19, 20 e 21.11.2003\n\nO trabalho prestado em domingos e feriados, não compensado, deve ser pago em dobro, sem prejuízo da remuneração relativa ao repouso semanal.",
    "VALOR MÍNIMO PARA EXPEDIR ALVARÁ AO INSS": "R$ 10,00\n\nNESTES CASOS, NÃO CONSTAR DA HOMOLOGAÇÃO O VALOR DEVIDO A TÍTULO DE INSS",
    

};    
    

function pesquisarTitulo() {
    var inputTitulo = document.getElementById("inputTitulo").value.toLowerCase();
    var resultados = document.getElementById("resultados");
    resultados.innerHTML = ""; // Limpa os resultados anteriores

    // Verifica se o campo de entrada está vazio
    if (inputTitulo.trim() === "") {
        return; // Retorna sem exibir resultados
    }

    Object.keys(titulosTextos).forEach(function(titulo) {
        if (titulo.toLowerCase().includes(inputTitulo)) {
            var li = document.createElement("li");
            li.textContent = titulo;
            li.onclick = function() {
                adicionarTexto(titulo);
            };
            resultados.appendChild(li);
        }
    });
}

function adicionarTexto(titulo) {
    var campoTexto = document.getElementById("campoTexto");
    if (campoTexto.value !== "") {
        campoTexto.value += "\n\n"; // Adiciona duas quebras de linha para espaçamento
    }
    campoTexto.value += titulosTextos[titulo]; // Adiciona o texto correspondente ao campo de texto
}

function limparTextarea() {
    document.getElementById("campoTexto").value = ""; // Limpa o conteúdo do campo de texto
}

function copiarTexto() {
    var campoTexto = document.getElementById("campoTexto");
    
    // Seleciona todo o texto na textarea
    campoTexto.select();
    campoTexto.setSelectionRange(0, 99999); // Para dispositivos móveis

    // Copia o texto selecionado para a área de transferência
    document.execCommand('copy');

    // Remove a seleção do texto
    campoTexto.setSelectionRange(0, 0);
}

// teclas home e end

const editable = document.getElementById('editable');

        editable.addEventListener('keydown', function(event) {
            if (event.key === 'Home') {
                event.preventDefault();
                const selection = window.getSelection();
                const range = document.createRange();
                range.setStart(this.firstChild, 0);
                range.collapse(true);
                selection.removeAllRanges();
                selection.addRange(range);
            } else if (event.key === 'End') {
                event.preventDefault();
                const selection = window.getSelection();
                const range = document.createRange();
                range.setStart(this.lastChild, this.lastChild.length);
                range.collapse(true);
                selection.removeAllRanges();
                selection.addRange(range);
            }
        });
